### ISSUE TITLE
Nesting Level

### ISSUE THREAD

**Issue by shane-scalable** [GrahamCampbell/Laravel-HTMLMin#68] opened 2017-03-10 18:39 UTC
Package looks great, but when I did a composer require I get this:

`$ php artisan vendor:publish

PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /var/www/influencer.co/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 647`

I removed the includes from app.php and re-ran which seemed to work fine, but i re-included them and ran '$ php artisan vendor:publish' and got the same error.  If I am going to release this package to a live server I am iffy about changing that nesting level as the system has a VERY high potential traffic load.

**Comment by GrahamCampbell** [comment] 2017-03-10 18:47
This looks more like an infinite loop in your code. There is no requirement to publish the config file also.

If the issue is not in your code, then it will likely be fixed by you manually deleting all the cache php files.

**Closed by GrahamCampbell** 2017-03-10 18:47 UTC
